name: Build and Push to Docker

on: 
  workflow_dispatch
    

env:
  PLATFORM: linux/amd64,linux/arm64


jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORM }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/personal-portfolio:${{ steps.package-version.outputs.current-version}}

  release-tags:
    runs-on: ubuntu-latest
    steps:
      -
        name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Create Release Tag
        run: 
          echo "Creating release tag"
          git tag -a v$${{ steps.package-version.outputs.current-version}} -m "Release v${{ steps.package-version.outputs.current-version}}"
          git push origin v${{ steps.package-version.outputs.current-version}}